name: 🚀 Feature request
description: Suggest an idea for this project
title: "Feat: "
labels: enhancement
type: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make CodeFactory Studio better.

        Please fill in as much of the following form as you're able.
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What alternatives have you considered?

  - type: textarea
    attributes:
      label: Anything else you want to share?
      description: Screenshots, mockups, links, or anything else that helps.